targets:
  $default:
    builders:
      confidential|confidential_builder:
        enabled: true

builders:
  confidential_builder:
    import: "package:confidential/builder.dart"
    builder_factories: ["confidentialBuilder"]
    build_extensions:
      "confidential.yaml": ["lib/generated/confidential.dart"]
    auto_apply: all_packages
    build_to: source
    runs_before: ["build_web_compilers|entrypoint"]
