name: confidential
description: Dart literals obfuscator to defend against static reverse engineering.
version: 0.4.0
repository: https://github.com/al-mohad/confidential.git

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  crypto: ^3.0.3
  archive: ^3.4.10
  pointycastle: ^3.7.3
  convert: ^3.1.1
  build: ^2.4.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.7

executables:
  dart-confidential: dart-confidential
